### ISSUE TITLE
已经部署完成了 怎么查看状态是否生效呢？

### ISSUE THREAD

**Issue by himonster1** [krwu/lhmon#4]
已经部署完成了 怎么查看状态是否生效呢？

**Comment by krwu** [comment]
如果是 docker run 部署的，用 docker logs {容器 id 或 name} 可以看到日志

如果是 docker-compose 部署的，用 docker-compose logs {服务名} 可以看到日志

正确运行的话，日志里会显示你设定的账号下有几台轻量服务器，每台的流量有多少，已用多少等信息。
